### ISSUE TITLE
Blog Comments

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/groupincome.org-old#11]
Per @taoeffect in #7 :
Blog entries with self-hosted commenting system that allows exporting comments. 
Preferably node.js or golang.

**Comment by taoeffect** [comment]
OK, I looked a bit and there doesn't seem to be anything good out there. Disqus seems to be the best for static sites. This is quite unfortunate.
- Isso - probably doesn't handle spam well. written in python.
- Discourse - ... it's forum software.
- Intense Debate - seems abandoned

Others: https://alternativeto.net/software/disqus/

Closing this for now, will post more in #7.

**Comment by dotmacro** [comment]
> Discourse - ... it's forum software.

From #7:

> [ties forum directly to blog](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963)

Discourse can automatically generate a new thread for each post, with that thread embedded on the post page as comments. This ties together discussion from people who find the topic via the forum itself (#4) to those who find the topic via the blog post. Seems like an elegant way to ensure the otherwise-separate discussions stay together.

For an example of how this looks in practice, check out the comments on [Coding Horror](https://blog.codinghorror.com/welcome-to-the-internet-of-compromised-things/#discourse-comments).

**Comment by taoeffect** [comment]
Yeah I know, I meant to say we already have a forum. See https://github.com/okTurtles/groupincome.org/issues/7#issuecomment-226057701
