### ISSUE TITLE
Changes needed for merging hexo site into master

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org-old#6]
Per [comment](https://github.com/okTurtles/groupincome.org/pull/5#issuecomment-216756630):
- [x] Remove no longer necessary stuff related to old site
- [x] make the `Powered by Hexo, theme by PPOffice` at the bottom a very light grey (barely visible), and have it just say "Using ___ Hexo theme" (making the blank the name of the theme, and a link to the direct theme repo, not a github profile).
- [x] Add instructions for how to generate and run the site locally (i.e. the commands to run) to README
- [x] Remove "Home" link at the top, the GI banner/logo already serves that purpose
- [x] Remove FAQ link at top, we're not ready for that yet.
- [x] ~~Remove search field thing from top right~~ **See [comment](https://github.com/okTurtles/groupincome.org/issues/6#issuecomment-223144340)**
- [x] Have copyright at the bottom include the start year of Group Income as well (2015-2016)
- [x] Include a screenshot of one of the slides in the center of the page and make it a link to the slides themselves (making it clear that it's a link to a presentation). I.e. a sort of "coming soon, and while you wait..." thing

**Comment by dotmacro** [comment]
> Remove FAQ link at top, we're not ready for that yet.

I've been drafting content for the FAQ and other pages. Do we not want a FAQ, or just not an empty FAQ? Or would we prefer a wiki?  

> Remove search field thing from top right

If we have a wiki/FAQ, should we still remove the search field?

**Comment by taoeffect** [comment]
> I've been drafting content for the FAQ and other pages. Do we not want a FAQ, or just not an empty FAQ? Or would we prefer a wiki?

So an FAQ page is good, a `Documentation` page is also good (for now, don't call it a wiki).

> If we have a wiki/FAQ, should we still remove the search field?

Good point, leave the search field if it actually does useful searching.
