### ISSUE TITLE
Blog section

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/groupincome.org-old#7]
- [x] Need a blog link in the nav
- [x] ~~Blog entries with some third-party commenting system (yes I know...) that at least allows exporting comments~~ Disqus comments 
- [x] Double-check markdown support, fix/note what's wonky
- [x] Double-check code highlighting
- [x] Front page of blog should show only summaries of posts the way [fixingtao.com](https://fixingtao.com) does
- [x] Individual posts _optionally_ display TOC
- [x] `year/month/day/title` permalinks

**Comment by dotmacro** [comment]
There are quite a few options for commenting systems. The two main contenders seem to be [Disqus](https://disqus.com/) and [Discourse](http://www.discourse.org/).

### Disqus
- pros: 
  - easiest (supported by hexo out-of-the-box)
  - well known (used by _everyone_)
  - includes comment moderation & spam controls
  - users can log in using G, fb, t (not gh)
- cons:
  - (free but) supported by ads (allow non-profit opt-out)
  - not open-source
  - rumors it doesn't play well with AJAX (n/a)

### Discourse
- pros: 
  - open-source 
  - [easy install](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md)
  - well known (used by _everyone else_)
  - [self-policing](https://meta.discourse.org/t/what-do-user-trust-levels-do/4924) -> [0 spam](https://news.ycombinator.com/item?id=6818956)
  - [ties forum directly to blog](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963) (forum addresses #4 )
  - users can log in using many existing social media services, _including github_
- cons:
  - (free but) requires paying for hosting (can self-host... see easy install link above)
  - not as well known, so may be less intuitive to some users who are used to Disqus

There's also [isso](https://github.com/posativ/isso), which I'll look into.

**Comment by taoeffect** [comment]
Awesome! Thanks for that beautiful comparison. Open source + self-hosting is the way to go! 😄 

If you think Isso might be better than Discourse I'd love to hear. :)

Also, as per your request for a reminder: make the side-nav bar TOC thing an optional per-post setting

**Comment by taoeffect** [comment]
OK, see my comment here: https://github.com/okTurtles/groupincome.org/issues/11#issuecomment-226054535

Per that, I'm really starting to have second thoughts as to the wisdom of using a static-site generator for a blog.

Here are [two](http://www.techelex.org/7-reason-not-choose-static-blog-generator/) [posts](http://www.multunus.com/blog/2014/02/migrated-back-wordpress-jekyll/) giving strong reasons to stick with WP for now. I'll summarize the points that jumped out at me (plus other ones that I thought of):
- The biggest issue: no matter what we do, comments are going to **require** us to either self-host and run server side software, or rely on some other server software to do all the commenting.
- All commenting solutions (whether self-hosted or hosted by third-parties), are terrible compared to self-hosted WP comments (SHWPC).
- SHWPC handles: email notifications, subscriptions, threading, import, export
- SHWPC avoids: advertisements, data silos, spam
- SHWPC is the right way to go. We could do a static site and attempt to "hook in to" our existing SHWPC to have it handle just the comments section, but I have not seen anyone do this and we don't have time to figure that out ourselves
- If the blog becomes popular and we have multiple authors, having fine-grained permissions (which WP allows) for who can edit what parts of the blog is super useful.
- With multiple authors on a static site, someone has to merge a PR and regen the site. That's much more painful than simply hitting "Publish"
- It's ultimately wrong for us to not host our own comments. We should be walking the walk, not just talking the talk. We must continue to set a good example if we're to push the decentralization message.

### So what do we do?

Unless you are cool with it, I don't want to just throw out all the amazing work you've put into this so far.

So some ways forward I see (and feel free to suggest more), include:
- **Option 1:** Go live with the static site for now and using [our forums](https://forums.okturtles.com/) to store the comments. I create a new forum where we create a thread for each blog post. Users can post there, we link to it from the blog, and later on we can even add and custom JS on our static site that asynchronously fetches and displays those comments on the blog itself. This is basically the Discourse method but without the Discourse. We're already running a forum. 😄 
- **Option 2:** Do the above, but immediately begin converting the theme (or finding a similar already existing one) and going full-blown WP, using [GeneratePress plugin](https://generatepress.com/) just like [Fixing Tao](https://fixingtao.com/) does.

Thoughts?

**Comment by taoeffect** [comment]
Pros (of Option 2):
- Don't have the multi-user issues that we might run into later on
- WP's Akismet is better at spam protection
- Sticking with WP lets us benefit from the rich community and plugin ecosystem
- WP will always have at least one great comment plugin. SMF (our forum software) has a smaller community and it's not clear how long it continue to live.

Cons (of Option 2):
- More work to do, but maybe not really if you count the work involved in having to write custom JS to fetch forum comments and display them
- Site is less secure (WP security issues)
- More sysadmin to deal with (=> more $ for upkeep). Could just throw the blog up on github instead.

OTOH, I honestly don't consider this wasted work, as:
1. It seemed (to me) like it was a great/very useful learning experience for you
2. It gives us more options to choose from. If WP ever stops work for us we can always go back to the static site

**Comment by dotmacro** [comment]
Some of the posts' anti-static points are irrelevant for our purposes, but you mentioned the relevant ones: multiple authors & comments. And sunk cost.

**Multiple Authors**
Multiple authors is definitely easier on WP. 👍  ([Gitlab has more fine-grained permissions](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/permissions/permissions.md) than Github, but they don't seem to help here.)

**Comments**

> WP's Akismet is better at spam protection

Akismet is impressive, but it might be on par with Discourse for spam protection. Some sites have zero spam with Discourse, without site-owner comment moderation. Discourse gives mod privileges to [all users](https://meta.discourse.org/t/what-do-user-trust-levels-do/4924). 

Discourse has a high memory requirement ([1GB](https://github.com/discourse/discourse/blob/master/docs/INSTALL.md)!), so SHWPC sounds better for now, but we can keep Discourse in mind at least to see what features we'd like to implement. [Note: if we switch to WP but want Discourse after all, there's a [WP Discourse plugin](https://github.com/discourse/wp-discourse/) we can try out.]

Pairing blog comments & forum threads is a great feature. We don't necessarily need Discourse to do this, but it's a feature we should implement.

**Sunk Cost**
Some of the work from the static site will carry over to WP just fine -- feature wishlist, picking a theme we like, customizing a theme that's close, etc. We can also use the current static site until WP is live. If WP works better, I'm fine with switching from hexo to WP.

**Conclusion**
WP is the best option for multiple authors, and a good option for self-hosted comments. If you think it will work out better, I'm fine with switching from hexo to WP. Whichever we choose, we should tie the blog comments to the forum, à la Discourse.

**Comment by taoeffect** [comment]
>  Some of the work from the static site will carry over to WP just fine -- picking a theme we like, customizing a theme that's close, etc. We can also use the current static site until WP is live. If WP works better, I'm fine with switching from hexo to WP.

Awesome, glad to hear that and sorry again for not thinking this through enough before. The earlier we notice these kinds of design issues the less of an issue they become later on. I think we caught this one reasonably early enough. :)

>  WP is the best option for multiple authors, and a good option for self-hosted comments. If you think it will work out better, I'm fine with switching from hexo to WP. Whichever we choose, we should tie the blog comments to the forum, à la Discourse. 

Thinking this through some more, while it's easy to code it to read & display comments from our forums, it's much more difficult to code it to post to them from the static site; sufficiently so that I think just going with SHWPC is the way to go.

So, as far as next-steps, let's do this (unless you see any issues):
- [x] Let's go with Disqus for comments, with the intent of exporting them and re-importing them into WP when we have that ready. Consider this issue closed for now, don't worry about code highlighting stuff, there's a WP plugin for that.
- [x] Make Hexo generate URLs that point to folders, not HTML files (so that it matches this URL structure: `https://fixingtao.com/2016/05/gregs-list-of-cool-companies-that-pledge-to-never-advertise-on-twitter/` (obv. domain not for fixingtao but for groupincome)
- [ ] Push your changes, send a PR.
- [ ] Begin looking for similar responsive and clean WP themes, make sure they're compatible with GeneratePress (I think most modern ones should be?)

I'll launch the static site and we'll move to WP shortly after; exporting & importing comments as appropriate.

**Comment by dotmacro** [comment]
> Let's go with Disqus for comments

Send me the shortname?
